name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
        
      - name: Build images
        timeout-minutes: 10
        run: |
          docker-compose build postgres
          docker-compose build api-gateway-lab5
          docker-compose build rental-service-lab5
          docker-compose build payments-service-lab5
          docker-compose build cars-service-lab5
      
      - name: Setup db
        run: |
          docker-compose up -d postgres
          docker-compose logs postgres
          sleep 5
          
          cd postgres
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < scripts/db-v3.sql
          cd ..
          
          cd auth_app_flask/scripts_DataBase
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < create_tables.sql
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < fill_cars_table.sql
          cd ..
          
      - name: Run containers
        timeout-minutes: 10
        run: |
          pip install PyJWT
          
          docker-compose up -d rental-service-lab5
          docker-compose up -d payments-service-lab5
          docker-compose up -d cars-service-lab5
          docker-compose up -d api-gateway-lab5
          
          docker-compose logs rental-service-lab5
          docker-compose logs payments-service-lab5
          docker-compose logs cars-service-lab5
          docker-compose logs api-gateway-lab5
          
          chmod +x ./scripts/wait-for.sh
          chmod +x ./scripts/wait-script.sh
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050
      
      - name: Wait 15s
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
          
      #- name: Run API Tests
        #uses: matt-ball/newman-action@master
        #with:
          # TODO insert your variant
          #collection: v3/postman/collection.json
          #environment: v3/postman/environment.json
          #delayRequest: 100
          #reporters: '[ "cli" ]'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and publish images
        timeout-minutes: 15
        run: |
          docker push ondubovickaya/api-gateway-lab5
          docker push ondubovickaya/rental-service-lab5
          docker push ondubovickaya/payments-service-lab5
          docker push ondubovickaya/cars-service-lab5
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      
      - name: Try the cluster !
        run: |
          kubectl get pods -A

      - name: Create Namespace
        run: |
          kubectl create namespace ondubovickaya
          
      - name: Deploy DB and services
        run: |
          kubectl get namespace
          
          cd k8s
          echo "------------------Deploy DB------------------"
          helm delete postgres --namespace ondubovickaya --ignore-not-found
          helm install -n ondubovickaya postgres ./postgres
          
          echo "------------------Deploy services------------------"
          helm delete cars --namespace ondubovickaya --ignore-not-found
          helm install -n ondubovickaya cars ./services
      
      - name: Wait 60s
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      
      - name: All resources from namespace ondubovickaya
        run: |
          kubectl get all -n ondubovickaya
      #- uses: education/autograding@v1
        # id: autograder
        # continue-on-error: true

      #- name: Github auto grader mark
        # uses: Romanow/google-sheet-autograder-marker@v1.0
        # with:
        #  google_token: ${{secrets.GOOGLE_API_KEY}}
        #  sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
        #  homework_number: 2
        #  user_column: 'D'
        #  column_offset: 'F'
        #  mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
